@echo off
del /S *.aux 2>nul
del /S *.bbl 2>nul
del /S *.bak 2>nul
del /S *.blg 2>nul
del /S *.out 2>nul
del /S *.thm 2>nul
del /S *.toc 2>nul
del /S *.synctex* 2>nul
del /S *.glg 2>nul
del /S *.glo 2>nul
del /S *.gls 2>nul
del /S *.ist 2>nul
del /S *.idx 2>nul
del /S *.ilg 2>nul
del /S *.ind 2>nul
del /S *.acn 2>nul
del /S *.acr 2>nul
del /S *.lof 2>nul
del /S *.lot 2>nul
del /S *.alg 2>nul
del /S *.glsdefs 2>nul